### ISSUE TITLE
大佬我想问问你之前给AutoMihoyoBBS这个项目写的captcha.py还在么

### ISSUE THREAD

**Issue by gggssepgf** [coolxitech/mihoyo#1]
万分抱歉到这个仓库下面发issue，因为以前的仓库被ban了，我也没备份，今天还不小心把本地文件删了，所以现在只能来问问大佬你那里还有没有了，就那个用人人ocr的（

**Comment by coolxitech** [comment]
> 万分抱歉到这个仓库下面发issue，因为以前的仓库被ban了，我也没备份，今天还不小心把本地文件删了，所以现在只能来问问大佬你那里还有没有了，就那个用人人ocr的（

在的，qq联系，6462175
